/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : task_template_list.h
**     Project     : ProcessorExpert
**     Processor   : MKL26Z128VLH4
**     Version     : Component 01.098, Driver 01.00, CPU db: 3.00.000
**     Compiler    : Keil ARM C/C++ Compiler
**     Date/Time   : 2013-04-18, 10:22, # CodeGen: 13
**
**     Copyright : 1997 - 2012 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file task_template_list.h                                                  
** @version 01.00
** @date 2013-04-18, 10:22, # CodeGen: 13
*/         
/*!
**  @addtogroup task_template_list_module task_template_list module documentation
**  @{
*/         


#ifndef __task_template_list_h__
#define __task_template_list_h__

/* MQX Lite task IDs */
#define INIT_TASK_TASK       1U
#define SHELL_TASK      2U
#define MMA8415_TASK            4U


/* MQX Lite task stack sizes */
#define INIT_TASK_TASK_STACK_SIZE (sizeof(TD_STRUCT) + 1024 + PSP_STACK_ALIGNMENT + 1)
#define SHELL_TASK_STACK_SIZE           (sizeof(TD_STRUCT) + 768 + PSP_STACK_ALIGNMENT + 1)
#define MMA8451_TASK_STACK_SIZE         (sizeof(TD_STRUCT) + 768 + PSP_STACK_ALIGNMENT + 1)

#endif /* __task_template_list_h__ */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0.13 [05.05]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
